#!/bin/bash

## Environment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Configurations
bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config normal_border_color "#4E76EA"
bspc config focused_border_color "#765DD1"

bspc config border_radius 0
bspc config window_gap 60
bspc config split_ratio 0.50
bspc config focus_follows_pointer true

# remove all rules first
# bspc rule -r *:*

# Kill if already running when refreshing
killall -9 sxhkd picom

# Lauch xsettingsd daemon
# xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Launch compositor in the background
picom -b &

# Launch polybar
polybar -r bsp-1

# Set wallpaper and color scheme
wal -i ~/Downloads/49417358927_98b3407244_o.jpg &

# Enable super keys for sxhkd
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

